### ISSUE TITLE
Correct Upside-down Mensuration Symbols

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#143]

**Comment by curran** [comment]
Part of #4

**Comment by seemantk** [comment]
![glyphs](https://user-images.githubusercontent.com/589271/27386482-dabc58b8-564a-11e7-9de6-5d56ee78a04b.png)

After a bit of playing with glyph alignments and transforms, I finally figured out how to redo the path to be upside down (use inkscape).  Fortunately, we don't have a lot of glyphs to have to consider, because this is a tedious process.

With the new paths, I'll try to render them again on the axis this week.

**Comment by curran** [comment]
Sweet!

**Comment by craigsapp** [comment]
The sneaky way to turn the glyphs upside down is with a `scale(1, -1)` to mirror the y-axis:

```xml
<symbol id="E909" viewBox="0 0 1000 1000" overflow="inherit">
   <path transform="scale(1,-1)"
         d="M210 113v38c-6 20 -17 23 -27 23h-125c-7 0 -18 0 -24 -23v-36c2 -18 6 -37 30 -37h121c8 0 19 5 23 23c1 4 2 8 2 12zM210 -136v26c-1 15 -4 31 -19 36c-3 1 -5 1 -8 1h-127c-17 -4 -21 -21 -22 -37v-22c2 -18 6 -37 30 -37h121c10 0 22 7 25 33zM223 557h9 c6 0 12 0 12 -17v-773v-311c0 -17 -6 -17 -12 -17h-9c-7 0 -13 0 -13 17v231v6c-2 18 -5 38 -30 38h-116c-24 0 -28 -20 -30 -38v-6v-470c0 -17 -6 -17 -13 -17h-8c-7 0 -13 0 -13 17v881v685c0 17 6 17 13 17h8c7 0 13 0 13 -17v-464v-10c3 -26 15 -33 25 -33h121 c25 0 28 19 30 37v227c0 17 6 17 13 17z"/>
</symbol>
```

**Comment by seemantk** [comment]
Closing as deprecated, since we are using @craigsapp's symbol set.
