### ISSUE TITLE
Show Ribbon drop-down failure in Safari

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/josquin-ribbon#183]
On the current gh-pages version, the "Show Ribbon" drop down seems to fail immediately upon choosing the other ribbon type, and reverts to being off in Safari. The behavior works as expected in Chrome and Firefox. I haven't tested IE or Edge. There are no errors or other output in the console.

![out](https://user-images.githubusercontent.com/4672869/31728724-ee5f8c42-b3e1-11e7-99f3-5a6f47937853.gif)

**Comment by curran** [comment]
Unfortunately I do not have access to a Safari browser (I'm on a Linux machine).

Are there any errors in the console when this happens?

**Comment by csbailey5t** [comment]
Unfortunately, there are no console errors.

**Comment by curran** [comment]
@seemantk To phrase it in another way - When you select an entry in the menu, the checkbox is toggled, but it shouldn't be

Perhaps somehow the events are getting confused, and the event of selecting a menu item is somehow causing the checkbox to get unchecked.

**Comment by curran** [comment]
I think the place to start debugging is `baton.js` line 163.

```js
162 // Show/Hide ribbons       
163 d3.select("#ribbons-ui").each(function() {
164   var check = d3.select(this).select("input")
165     , choice = d3.select(this).select("select")
166     , callback = check.node().id // callback name == checkbox 'id'
167   ;                        
168   // Hide the ribbon dropdown initially
169   choice.style("display", "none");
170 
171   check.on("change", function(d) {    
172       choice.style("display", this.checked ? null : "none");
173       var value = choice.node().value;
174       signal.call(callback, this, this.checked ? value : this.value);
175     })
176   ;
177   choice.on("change", function() {    
178       signal.call(callback, this, this.value);
179     })
180   ;
181 });
```

**Comment by curran** [comment]
One thing that would explain the behavior is if `this.value` evaluates to `null` on line 178.

I'd be interested to see what gets printed in Safari with a debug statement like this:

```js
   choice.on("change", function() {
       console.log(this.value); // Should print the selected value, may print null in Safari?
       signal.call(callback, this, this.value);
     })
   ;
```

**Comment by curran** [comment]
@seemantk @csbailey5t @craigsapp So I added that debug statement in this branch https://github.com/sul-cidr/josquin-ribbon/pull/188

If anyone with Safari can run that code and try to replicate the bug, then post the output in the console here, that would be helpful :smile:

**Comment by csbailey5t** [comment]
@curran I actually had to click the select a few times to get any output, but eventually got:

`[Log] The following value should not be null: (josquin.js, line 1582)`
`[Log] attack_density (josquin.js, line 1583)`

I get the same output from those console logs in Chrome. That functionality seems consistent, which makes it seem more likely that, for some reason, it is simply causing the ribbon to become unchecked upon selection.

**Comment by craigsapp** [comment]
Here is some debugging information and the solution (at the bottom, so you can skip the debugging process writeup):

--------


Here are the signals from baton.js:

```javascript
function createSignals() {

    // Pass each event into notesBook via accessors.
    signal
        .on("show-notes",      notesBook.notes)
        .on("show-extremes",   notesBook.extremes)
        .on("hilite",          notesBook.hilite)
        .on("show-ribbon",     notesBook.ribbons)
        .on("separate-voices", notesBook.separate)
        .on("zoom",            notesBook.zoom)
    ;

    // Update the duration indicator on zoom.
    signal.on("zoom.durationIndicator", function (extent){
        var duration = (extent[1] - extent[0]) / 10;
        var message = duration + " seconds selected";
        d3.select("#zoomed-duration-indicator").text(message);
    });
} // createSignals()
```

The `show-ribbon` signal is related to the problem.  This is linked to the function `notesBook.ribbons`.

`notesBook.ribbons` is this function in `notesbook.js`:

```javascript
  my.ribbons = function(arg) {
console.log("RIBBONS FUNCTION ARG=", arg);

      // TODO move this into render function, introduce variable.
      voices.selectAll(".ribbon")
          .style("display", function(d) {
              return d.toLowerCase() === arg ? "inline" : "none";
            })
      ;
    } // my.ribbons()
  ;
```

I added the `console.log` message.  Clicking on the "Show Ribbon" checkbox, this message gets displayed on the console:

<img width="471" alt="screen shot 2017-10-25 at 7 54 51 pm" src="https://user-images.githubusercontent.com/3487289/32032935-76593864-b9be-11e7-9463-04157b875b01.png">

Selecting The attack density from the dropdown menu, two more messages are added:

<img width="428" alt="screen shot 2017-10-25 at 7 55 56 pm" src="https://user-images.githubusercontent.com/3487289/32032950-8c5a1246-b9be-11e7-88a4-229939a853a2.png">


The second message is the one which is causing the problem.  Since it is "all", then the menu's display will be set to `none` and it disappears.

----

Double checking in Chrome seems to confirm the bug in Safari, as only two messages are generated for the two actions rather than three:

<img width="376" alt="screen shot 2017-10-25 at 7 57 39 pm" src="https://user-images.githubusercontent.com/3487289/32033003-d50696fe-b9be-11e7-9c93-b238ee415d27.png">

---

The "all" value is generate by something unchecking the "Show Ribbon" check box automatically.  If the checkbox is deselected in Chrome, the "all" message comes through, which in turn hides the menu as expected:

<img width="770" alt="screen shot 2017-10-25 at 8 29 09 pm" src="https://user-images.githubusercontent.com/3487289/32033766-4e81a006-b9c3-11e7-906d-3da910421fac.png">

----

In `baton.js`, these functions in connectSignalsToDOM() are involved:

```javascript
    // Show/Hide ribbons
    d3.select("#ribbons-ui").each(function() {
      var check = d3.select(this).select("input")
        , choice = d3.select(this).select("select")
        , callback = check.node().id // callback name == checkbox 'id'
      ;
      // Hide the ribbon dropdown initially
      choice.style("display", "none");

      check.on("change", function(d) {
          choice.style("display", this.checked ? null : "none");
          var value = choice.node().value;
console.log("%cGOT HERE 1 value:", "color:purple", value, "   this.value:", this.value, "    arguments:", arguments, "d:", d);
          signal.call(callback, this, this.checked ? value : this.value);
        })
      ;
      choice.on("change", function() {
console.log("%cGOT HERE 2 this:", "color:green", this, "   this.value:", this.value, "    arguments", arguments);
          signal.call(callback, this, this.value);
        })
      ;
    });
} // connectSignalsToDOM()
```

In Chrome, the above colored messages added to the debugging statements are:

<img width="851" alt="screen shot 2017-10-25 at 8 37 30 pm" src="https://user-images.githubusercontent.com/3487289/32033909-57580034-b9c4-11e7-97a4-c8ec60b10a84.png">

The purple message is related to activating the checkbox for "Show Ribbon", the green messages is related to selecting the "Activity Density" from the menu.

If I uncheck the "Show Ribbon"  checkbox this message gets displayed:

<img width="729" alt="screen shot 2017-10-25 at 8 39 05 pm" src="https://user-images.githubusercontent.com/3487289/32033948-9219a59c-b9c4-11e7-970c-7a18b45f6e5c.png">

In Safari there is an extra action of unchecking the "Show Ribbon" option when the "Attack Density" menu item is selected:

Clicking on the checkbox for "Show Ribbon" generates this debug statement:

<img width="523" alt="screen shot 2017-10-25 at 8 40 16 pm" src="https://user-images.githubusercontent.com/3487289/32033988-c498f766-b9c4-11e7-9678-c56961f52d77.png">

Selecting "Attack Density" generates two messages, with the second one turning off the checkbox for the "Show Ribbon":

<img width="598" alt="screen shot 2017-10-25 at 8 41 21 pm" src="https://user-images.githubusercontent.com/3487289/32034002-e4037b30-b9c4-11e7-9246-da80fbee56a8.png">

-----
 Solution
============

In `/index.html` there is a `<label>` element which is wrapped around both the checkbox and the select menu.  The solution is to only wrap it around the checkbox (and more importantly the following text), and do not include the `<select>` element:

```
                   <label for="show-ribbon">
                      <input id="show-ribbon" type="checkbox" value="all"> Show Ribbon: 
                  </label>
                  <select id="select-ribbon">
                        <optgroup label="Select a Ribbon">
                          <option value="standard_deviation">Melodic Contour</option>
                          <option value="attack_density">Rhythmic Activity</option>
                        </optgroup>
                  </select>
```

Strictly speaking, Safari is probably behaving correctly: when clicking on the menu box, you are requesting that the checkbox state be changed as well.  Google Chrome probably auto-corrects this bug and/or only allows the `label@for` to affect plain text, since obviously this it would not be intended to change two form elements at the same time with one action.

Clicking on the "Show Ribbon" option in Safari:

![screen shot 2017-10-25 at 9 16 26 pm](https://user-images.githubusercontent.com/3487289/32034811-d52ef09e-b9c9-11e7-8108-2703b8924144.png)

Selecting "Attack Density" ribbon from the menu in Safari (notice that the menu does not disappear):

![screen shot 2017-10-25 at 9 16 29 pm](https://user-images.githubusercontent.com/3487289/32034814-e4c6f984-b9c9-11e7-93b5-c44dcbb0e282.png)

Unchecking the "Show Ribbon" option in Safari:

![screen shot 2017-10-25 at 9 16 32 pm](https://user-images.githubusercontent.com/3487289/32034825-f28c2d50-b9c9-11e7-9bc0-20725dda5641.png)

Chrome behaves the same (no problem as before the change of label).

Q.E.D.

**Comment by curran** [comment]
Hmm. That looks like what we'd expect. So our issue is elsewhere.

**Comment by curran** [comment]
Let's continue the discussion on https://github.com/sul-cidr/josquin-ribbon/pull/188

**Comment by curran** [comment]
Thanks @craigsapp ! I added your solution in this pull request https://github.com/sul-cidr/josquin-ribbon/pull/188
