### ISSUE TITLE
Horizontal pitch reference lines and labels

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#6]

**Comment by curran** [comment]
I wonder what notes these should correspond to.. We can look to the original Ribbon plot as an example and use the same notes used there https://github.com/sul-cidr/ribbon/blob/master/index.html#L510

**Comment by curran** [comment]
Relevant code snippets:

``` js
  function staffAxisFormat(num) {
    var staffLabels =
    { "38": "F",
      "36": "D5",
      "34": "B",
      "32": "G",
      "30": "E",
      "28": "C4",
      "26": "A",
      "24": "F",
      "22": "D3",
      "20": "B",
      "18": "G"
    }
    return staffLabels[num];
  }
```

Awesomely, a D3 axis was used for rendering the lines:

``` js
    yAxis = d3.svg.axis()
        .scale(pitchScale)
        .orient("right")
        .tickSize(vizWidth)
        .tickSubdivide(false)
        .tickFormat(staffAxisFormat);    
    d3.select("#axes").selectAll("g.part").call(yAxis);
    d3.selectAll("g.tick")
        .filter(function(d) {return d == 28})
        .style("stroke-dasharray", "4 4");
```

I think this may also be relevant, though not sure exactly what it does:

``` js
  d3.select("g#axes").select("." + parts[x])
        .selectAll("g.tick")
        .filter(function(d) {return d != 28 && d != 24 && d != 32})
        .remove();
```

**Comment by curran** [comment]
Notes from our call with Josquin team:
- Middle C should be in the middle
- Bottom line should be F 24
- Top should be G 32

**Comment by craigsapp** [comment]
Yes

**Comment by curran** [comment]
More notes: We should make a clear configuration structure that says
- which notes to use as lines, and
- how each note should be represented

The goal here would be to make it easily configurable in the future (e.g. to show a full staff).

**Comment by craigsapp** [comment]
> ```
>   function staffAxisFormat(num) {
>     var staffLabels =
>     { "38": "F",
>       "36": "D5",
>       "34": "B",
>       "32": "G",
>       "30": "E",
>       "28": "C4",
>       "26": "A",
>       "24": "F",
>       "22": "D3",
>       "20": "B",
>       "18": "G"
>     }
>     return staffLabels[num];
>   }
> ```

These are the staff lines on the vertical scale, using diatonic pitches (7 notes per octave):

![screen shot 2016-08-31 at 6 13 52 pm](https://cloud.githubusercontent.com/assets/3487289/18136973/e76d864e-6fa6-11e6-846d-925355b5d562.png)

The pitches are extractable from the numbers.  For example, the _pitch-classes_ (pitches without the octave information) are:

```
0 = C
1 = D
2 = E 
3 = F
4 = G
5 = A
6 = B
```

So for middle C, which is in the 4th octave in [scientific pitch notation](https://en.wikipedia.org/wiki/Scientific_pitch_notation), is the integer for the C pitch-class (0) plus the octave (4) times 7 (the number of pitch classes):

```
C4 = 0 + 4 * 7 = 28
 pc + octave * base = number
```

Example for F3:

```
F3 = 3 + 3 * 7 = 24
```

These are the units of the vertical axis for the ribbon plot that will be used (exclusively) in the JRP version of the ribbon plot.

---

The vertical position units of the horizontal lines will preferably be easy to change (just needed on the backend, no user-selectable changes).  Ideally there would be an array of objects describing the lines something like this:

``` javascript
[
{pitch: 32, label: "G", style: "solid"},
{pitch: 28, label: "C4", style: "dashed"},
{pitch: 24, label: "F", style: "solid"}
]
```

The _style_ parameter you can decide how to describe if there is a better way to do it (such as a list of CSS/SVG stylings to apply to the line, or two classes such as "solid", "dashed" to control the styling, or hard-coding "solid" to draw a solid line and "dashed" to draw a dashed line).

An alternate option would be to add twelve-tone numbers into the line objects:

``` javascript
[
{b7: 32, b12: 67, label: "G", style: "solid"},
{b7: 28, b12: 60, label: "C4", style: "dashed"},
{b7:24, b12: 53, label: "F", style: "solid"}
]
```

`b7` = base-7 (diatonic) note number and `b12` = base-12 (twelve-tone) note number.  Then there would be a global variable which specifies which base should be used:

``` javascript
     var PITCH_UNIT = "b7";
```

Then someone could use the twelve-tone scale by changing this to:

``` javascript
     var PITCH_UNIT = "b12";
```

Notice that all notes have a `b7` and `b12` parameter in their `pitch` value in the input JSON data (sample note at the bottom of this message), and the same global variable could be used to control which units they use for the vertical axis as well:

A useful generalization to build into the code is the ability to switch to the twelve-tone representation.  This has 12 pitch classes per octave:

```
0 = C
1 = C#/Db
2 = D 
3 = D#/Eb
4 = E
5 = F
6 = F#/Gb
7 = G
8 = G#/Ab
9 = A
10 = A#/Bb
11 = B
```

```
C4 = 0 + (4+1) * 12 = 60
 pc + (octave+1) * base = number
```

A caveat is that I am using MIDI note numbers for twelve-tone pitches.  Middle C is placed on octave "5" in MIDI, so that is what the extra +1 is for (confusing, but it would be more confusing if I matched the octave numbers for middle C in the two representation systems).

Example for F3:

```
F3 = 5 + (3+1) * 12 = 53
```

Here are the equivalent staff line numbers as MIDI note numbers (twelve-tone pitches, using 5 for the middle C octave):

![screen shot 2016-08-31 at 6 22 23 pm](https://cloud.githubusercontent.com/assets/3487289/18138661/192f1628-6fae-11e6-9e36-7a5eb8dc2c14.png)

---

Notice in the JSON data input into the ribbon plot, both the base-7 (diatonic) and base-12 (twelve-tone) pitch representations are given for each pitch:

http://josquin.stanford.edu/cgi-bin/jrp?a=proll-json&f=Das1002a

``` json
                {
                    "pitch"     :   {"name":"G4", "b7":32, "b12":67},
                    "starttime" :   [0],
                    "duration"  :   [16],
                    "metpos"    :   [1]
                },
```
